services:
  postgres:
    container_name: zenith-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: zenith
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - zenith-network

networks:
  zenith-network:
    driver: bridge

volumes:
  postgres-data:
