spring:
  application:
    name: zenith
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

app:
  jwt:
    secret: your-generated-secret-key-here
    expiration: 900000 #15 minutes in milliseconds

logging:
  level:
    root: info
